name: SIT Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/sit.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar -xzf geckodriver-v0.30.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Build with Maven
        run: mvn clean install
        working-directory: .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run unit tests Build and test
        run: mvn test -Dwebdriver.gecko.driver= geckodriver
        working-directory: ./Tech_JavaProject


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to SIT
        run: |
          echo "Deploying to SIT environment"
          
